### ISSUE TITLE
Inkompatiblität mit dem DSGVO System

### ISSUE THREAD

**Issue by DrCarsonBeckett** [derUli/emojis_for_ulicms#4]
Moin moin,

sobald man die Checkbox für die DSGVO nutzen will wird der Text mit einem html Code angezeigt.
Sobald die Emoji Plugins entfernt sind, funktioniert dieses einwandfrei.
Genaueres liegt wohl an dem [checkbox] Text, denn wenn dieser entfernt ist und die Plugins noch installiert sind, funktioniert die Wiedergabe problemlos. Sobald Checkbox in rechteckigen Klammern steht, ist wieder eine HTML Code ausgabe.

**Comment by derUli** [comment]
Die Funktion, welche die Unicode-Emojis durch eine HTML-Darstellung ersetzt, wird auf den gesamten HTML-String angewendet.
Dadurch, dass die Checkbox als Value ein Emoji-Häkchen übrträgt, wird somit das Value durch html Code ersetzt.

Das Problem muss gelöst werden, in dem per DOMDocument alle Text Nodes ermittelt werden und die Funktion zum Anwenden der Emojis nur auf Text Nodes durchgefhürt wird.

https://stackoverflow.com/questions/768737/dom-fetch-all-text-nodes-in-the-document-php

**Comment by derUli** [comment]
```php

$html = file_get_contents("https://www.ulicms.de");
$html = trim($html);
// Create a new DOM document
$dom = new DOMDocument();
    // Parse the HTML. The @ is used to suppress any parsing errors
    // that will be thrown if the $html string isn't valid XHTML.
@$dom->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);

$xpath = new DOMXPath($dom);
$textnodes = $xpath->query('//text()');
foreach($textnodes as $node) {
        // TODO: Statt den textContent auszugeben, die Emojis daran mit emoji_unified_to_html() ersetzen. Zum Schluss der Funktion das gesamte DomDocument als html zurückgeben
        var_dump($node->textContent);
}
```

**Comment by derUli** [comment]
Ich werde im Laufe der Woche die Version 1.2, die ich dir bereits gestern per Mail geschickt habe, offiziell veröffentlichen.
Da ist der Bug bereits korrigiert.
